site_name: SimpleHome-Wiki

repo_name: SimpleHome-Server
repo_url: https://github.com/SimpleHome-Server/

site_url: https://simple-home.github.io/docs/
edit_uri: edit/master/docs/
theme:
  name: material
  logo: https://raw.githubusercontent.com/Simple-Home/SimpleHome-Client/master/src/assets/logo.png
  palette:
    accent: light green
    primary: light green
markdown_extensions:
  - codehilite
  